[package]
name = "fmbq-timer-rs"
version = "2.0.0-alpha.1"
edition = "2021"

[lib]
name = "fmbqtimer"
crate-type = ["cdylib"]

[[bin]]
name = "fmbqtimer"
path = "src/main.rs"

[dependencies]
hound = "3.5"
log = "0.4"
shadow-rs = "0.23"

[dependencies.eframe]
version = "0.22"
features = ["android-native-activity"]

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11"

[target.'cfg(target_os = "android")'.dependencies.ndk]
version = "0.7"
features = ["audio"]

[target.'cfg(target_os = "android")'.dependencies.winit]
version = "0.28"
default-features = false
features = ["android-native-activity"]

[target.'cfg(not(target_os = "android"))'.dependencies]
env_logger = "0.10"

[build-dependencies]
shadow-rs = "0.23"
