[package]
name = "fmbq-timer-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "fmbqtimer"
crate-type = ["cdylib"]

[dependencies]
log = "0.4"

[dependencies.eframe]
version = "0.22"
features = ["android-native-activity"]

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11"

[target.'cfg(target_os = "android")'.dependencies.winit]
version = "0.28"
default-features = false
features = ["android-native-activity"]

[target.'cfg(not(target_os = "android"))'.dependencies]
env_logger = "0.10"
