[providers.keychain]
type = "keychain"
service = "fnox"

[providers.age]
type = "age"
recipients = [
    "age18awmjqdnafxshg8tx5a4p2e5kemz890hzlkaphgl23gdr0hh6axq2fcgqt", # sagebind
    "age1wrmsy0fjc0cjdfvnj9ykv4l0xcmyg6l8f9pk0tuw7lk9jt4u8yksvn9vnf", # ci
]
identity = {
    provider = "keychain",
    value = "age-key",
}

[secrets]
CARGO_APK_RELEASE_KEYSTORE= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UEtRUlNHdk9XYWM1MXIyZFdRdFI4VFBIN29senh4dnV6ay9CeTRGQ1dVCit3MkhtQ3pPeEZTK0pqK2VYbHFGWHNWYS9RdjJ3OUV6RGg2b0VkY09ETVkKLT4gWDI1NTE5IE45VTgxUTJybElBd0pZb3lmUm5zSFBpenB2MUZCekIvMEwxM3JyTmVYVkUKaFZhVFJ5QU96WGR6eU9XS3dEQ0J4clFtbkowWkY2aDlEMG5IWStxbGtjZwotPiA7ZXxHcS1ncmVhc2UgVzp1XWt6cWAgYH0hWn1BIGcrCndLQWJYaWZPMVV5NEJzM0VnZXVWY055M2pRM0lFNy91eExlWElqOFZUWDhUSjBJaW1CMW9DQVNNSnhFbG9iWWUKSUtSSTE5MWVlanhPMU9WbjFENjZCRmhWTXNCWlRzNnJ2eWd5TTVwUG1BSUZBZwotLS0gWDIwQ1ZjWWVERkdsMVBVWDNwdlViNXJxYlN3S2d1L3k2NjlXSFZQTWVzUQpEatl9ZnX+lVVNX2Lc3Q314pdRWgPAokfG2b7BDW5wp4AzI9uy0Lijsyga1G7b8qgRYbXXkNmimTbv1zTDM45ZCulfxepi9y6hqu5EPbuxzgF+w2ckw5mwgw==" }
CARGO_APK_RELEASE_KEYSTORE_PASSWORD= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMb1BJN1hOU0lWaFF3dmZFWjQ2YTR1N0VvQjllckNYSTNCMkw2YXhJRW1FCmlCU1FMdm8xcWFIRGdaNU43RFZuNmtUVkJJZXlEdmdUTDdHWTV6V3U1U0EKLT4gWDI1NTE5IG5oWXM0T0NLck9WSW5FUkd6d2R6UFRrZVBLazRRRGo4Y3dnZFp3ZjFXMTgKOUpPd29aeG9kSGdQRmJyTVdQbTF6SWhMRHpLVXA3MHVwSXNURWFMSnJpbwotPiBmIkZGLWdyZWFzZSBzIGBsfCBAUDM7KzE4IExQClJ4YnhkTUF3NXI4c1drbWZwY2NqNUxGc0xIc2xRRXpYZUlJbWJHVGJGV2JTWmk1MFVxbFhSZlVlMnZESVR3Ci0tLSBZSFBOcWF3bTBKODNnQTEvVlhEK0pRR0RnaXpzZE9IYklLVG83R2pDS2pjCgwyVslhENxVKHOPdMhwUA6WPMC7rMywy8IdMEL19xYAozrx93qrJN+4Vik=" }

[profiles.ci.secrets]
CARGO_APK_RELEASE_KEYSTORE= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bG8vVEl3a2VGdXF4ampkaUIvdmV2U3NCSUhjb0RVVU1BZ3krZEpGQnhzCjFoUE56WW9PMDF1NEtmdWVvd1BzbFVsSTVsRmRqYXExbTNOdTI5dGxIemsKLT4gWDI1NTE5IEhLNUFuZ1EwM2FDWWd3UnppL1dpbmxBalJWb1dDYXByOXplYzlFSWpUQzQKWEZkTGh6Y0ZYdnZncm5MSUFaUSt3M3FMU0tobWZnTm83QkdGVGt2OGpPYwotPiArb2MjLWdyZWFzZSArRlhvSFwKOWZBTjJVVCs2QnRhbWRsOWVWS2tMOEROWDd0NjV5cnJkQXZaK05pVnAwa0YwdDU5SitxMnR3TQotLS0gSVlVNkRTV3VlTmJDdFdNeHZlUktHR3pvZmk3emt1TlZOb3pNOXVaZ1NTdwqGBhA2FkI7OGTAOfhy7u/wJxydwBE60MU1y4PD53VkRYmGRdHGqX2iSfS7wpghYoaJnVhhxQ==" }
