version = 1

[install]
# Use a local Flake to build a custom Android SDK environment.
android-sdk.flake = "path:nix/android-flake#android-sdk"
cargo-ndk.pkg-path = "cargo-ndk"
inkscape.pkg-path = "inkscape"
make.pkg-path = "gnumake"

# apksigner.pkg-path = "apksigner"
# android-tools.pkg-path = "android-tools"
# aapt.pkg-path = "aapt"
# bundletool.pkg-path = "bundletool"

[hook]
on-activate = '''
  export ANDROID_HOME=$FLOX_ENV/share/android-sdk
'''

## Services ----------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
## -------------------------------------------------------------------
[services]
# myservice.command = "python3 -m http.server"

[build.unsigned]
description = "Build an unsigned APK"
command = '''
  make target/apk/org.fmbq.timer-unsigned.apk
  mkdir -p $out/share
  cp target/apk/org.fmbq.timer-unsigned.apk $out/share/org.fmbq.timer-unsigned.apk
'''

[options]
systems = ["x86_64-linux"]
