name: ci
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4

      - name: Build
        run: mise run app:build

      - uses: actions/upload-artifact@v7
        with:
          name: org.fmbq.timer.apk
          path: target/debug/apk/fmbqtimer.apk
