name: ci
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build
        run: devenv tasks run app:build

      - uses: actions/upload-artifact@v4
        with:
          name: org.fmbq.timer-unsigned.apk
          path: target/apk/org.fmbq.timer-unsigned.apk
