name: ci
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Build
        run: make -j4 target/apk/org.fmbq.timer.dev-unsigned.apk

      - uses: actions/upload-artifact@v3
        with:
          name: org.fmbq.timer.dev-unsigned.apk
          path: target/apk/org.fmbq.timer.dev-unsigned.apk
